apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: operator-admin
    httpscaledobjects.http.keda.sh/version: {{ .Values.images.tag | default .Chart.AppVersion }}
    keda.sh/addon: {{ .Chart.Name }}
    app: {{ .Chart.Name }}
    name: "{{ .Chart.Name }}-{{ .Values.operator.adminService }}"
    app.kubernetes.io/name: "{{ .Chart.Name }}-operator-admin"
    app.kubernetes.io/version: "{{ .Values.images.tag | default .Chart.AppVersion }}"
    app.kubernetes.io/component: operator-admin
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{ tpl .Values.additionalLabels . | indent 4}}
  name: "{{ .Chart.Name }}-{{ .Values.operator.adminService }}"
  namespace: "{{ .Release.Namespace }}"
spec:
  ports:
  - name: admin-http
    port: {{ default 9091 .Values.operator.adminPort }}
    targetPort: admin-http
  selector:
    control-plane: controller-manager
